---
# application.yml  
spring:
  oauth2:
    client:
      # These client credentials are the result of GitHub registration, 
      # and assume one is running the client on localhost:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      userAuthorizationUri: https://github.com/login/oauth/authorize
      accessTokenUri: https://github.com/login/oauth/access_token
      clientAuthenticationScheme: form
    resource:
      # Not sure what this is for, but the token exchange bit won't work without it.
      userInfoUri: https://api.github.com/user
      # This appears to be optional:
      preferTokenInfo: false
      
# For some reason, we need to turn basic security off,
# otherwise we will be prompted for credentials unprotected resources.
security.basic.enabled: false      